### ISSUE TITLE
Do not require RWX PVs.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#148]
Many users clusters (especially in cloud) don't provide storage classes that support RWX.
Solution: The addons will download/upload files (trees) instead.  The maven optimization provided by sharing the m2 cache using RWX can also be accomplished by using a maven proxy.
To support this, the bucket API will need to be augmented to support GET/POST/PUT of file trees.

### API

Bucket owner endpoints will honor `X-Directory` = (archive|expand) header as follows:

GET /applications/1/bucket/windup/report  _Report is a directory (tree)._
- *When*: no header, will stream back index.html.
- *When*: path references a directory and `X-Directory:archive` build a tarball of the directory and stream it back with `X-Directory:expand`.

PUT /applications/1/bucket/windup/report _Report is a directory (tree)._
- *When*: no header, store the .tar.gz (body) as a file at the specified path.
- *When*: `X-Directory:expand` replace the file/directory at the specified path with the content of the tarball (streamed).

Example curl commands.

GET the index page ( as current):
```
$ curl localhost:8080/applications/1/bucket/windup/
$ curl localhost:8080/applications/1/bucket/windup/index.html
```

GET the report as an tarball.
```
curl -H "X-Directory:archive" localhost:8080/applications/1/bucket/windup (must be directory)
```

GET a file (as current).
```
curl localhost:8080/applications/1/bucket/windup/file.pdf
```

Upload and replace a **file** (even if it's a tarball).
```
curl -X PUT -F "file=@file.tar.gz" localhost:8080/applications/1/bucket/some-dir/file.tar.gz
```

Upload and expand an tarball to replace a **directory**.
```
curl -v -X PUT -H "X-Directory:expand" -F "file=@data.tar.gz" localhost:8080/applications/1/bucket/windup/report
```

### Binding

The `Go` binding provided for addons will be enhanced to include bucket content management methods.
- Task.Bucket()
     Get associated bucket object.
- Application.Bucket()
     Get associated bucket object.
- Bucket.Get()
     Download files/directories _from_ the bucket.
- Bucket.Put()
      Upload files/directories _to_ the bucket.
- Bucket.Delete()
      Delete files/directories in the bucket.

Examples:
```
//
// Download
bucket = addon.Task.Bucket()
err = bucket.Get("uploaded/x.war")
//
// Upload
bucket := addon.Application.Bucket()
err = bucket.Put("windup/report", "/working/report")
```

## Maven Cache

Make RWX optional.
Add rwx_supported (bool) default: true to the operator. The operator will set `RWX_PVC` envar in the UI and Hub pods.
General:
- The Hub will
  - remove the `Volume` model.
  - remove the volume manager.
  - API /volumes endpoint will have a single sub-resource `/volumes/rwx` with support for GET and POST on `/volumes/rwx/clean` Both GET and clear will be executed synchronously in the endpoint.
  - The Addon controller will no longer populate the /volumes.
- The _admin_ addon will be removed.
- The `mounts` construct will be removed from Addon CR.  (no longer updated by operator), 
- The Windup addon will set the m2 cache directory to  `/mnt/shared/m2` when using Maven.
When RWX supported:
- The Hub will mount the RWX volume in task pods at `/cache`.
When RWX not supported:
- The Hub will mount an EmptyDir volume in task pods at `/cache`
- The UI will omit the maven `Local Artifact Repository` size field and `clean` button.
- The tackle-maven PVC will be renamed to tackle-cache PVC and will only be created when RWX supported.

**Comment by aufi** [comment]
Confirm I'm working on the tar.gz GET&PUT actions that could be reused for this issue. I'd have few questions just to be sure.

Using a "sub-path" within bucket owner endpoint - agreed :+1:  - this assumes that the owner has just one bucket - is this going to be right also in close future?

The approach using Accept/Content-Type headers looks reasonable to me :+1: 

Not critical, but I was looking on mimetypes used for downloading tar.gz files, it looks the typically used mimetype is ```application/x-gzip``` (gin gonic sets it when sending a tar.gz file, kernel.org sends it for compressed tar with Linux kernel sources). Could the mimetype be  ```application/x-gzip``` at least for a beginning or open to be discussed? (```application/x-gtar``` looks to me to represent a tar somehow compressed, not necessary using gzip)

If we used a caching proxy, we might need implement HEAD or similar method to provide headers saying if given archive is up-to-date (like Last-Modified based on modification time of files in the bucker directory).

**Comment by jortel** [comment]
> Confirm I'm working on the tar.gz GET&PUT actions that could be reused for this issue. I'd have few questions just to be sure. 

Yes.

> Using a "sub-path" within bucket owner endpoint - agreed +1 - this assumes that the owner has just one bucket - is this going to be right also in close future?

Yes.

> Not critical, but I was looking on mimetypes used for downloading tar.gz files, it looks the typically used mimetype is `application/x-gzip` (gin gonic sets it when sending a tar.gz file, kernel.org sends it for compressed tar with Linux kernel sources). Could the mimetype be `application/x-gzip` at least for a beginning or open to be discussed? (`application/x-gtar` looks to me to represent a tar somehow compressed, not necessary using gzip)

Fine with whatever is appropriate.

> 
> If we used a caching proxy, we might need implement HEAD or similar method to provide headers saying if given archive is up-to-date (like Last-Modified based on modification time of files in the bucker directory).
