### ISSUE TITLE
bug: in v2.1.2 enabling authentication means you can no longer run addons

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/tackle2-hub#197]
# Bug

The default instructions to install Tackle 2 Hub enable authentication. There's currently no workaround for running addons when auth is enabled.

# Steps to reproduce

1. Run Tackle 2 Hub v.2.1.2 by following the instructions on https://konveyor.github.io/tackle/installation/
2. Create an application.
3. Install an addon like https://github.com/konveyor/addon-move2kube
4. Try to run the addon on the application using `curl`
```
curl -i -X POST localhost/hub/tasks -d \
'{
    "name":"move2kube",
    "state": "Ready",
    "locator": "move2kube",
    "addon": "move2kube",
    "application": {"id": 1},
    "data": {}
}'
```
5. Get a 401 unauthorized response.

# Context

The instructions install Tackle 2 Hub with the default settings, i.e. authentication enabled.

In the current version, to run an addon you need to use the API. To use the API all requests need an `Authroization: Bearer xxxx` header with an access token.

Currently there's no way to obtain the JWT access token through the UI. The user management screen as an admin only lets you edit your own personal info, etc. You can try to copy the admin user's access token from the browser but that token only has permission to list applications, tasks, etc. It does not have the scope necessary to run an addon.

Adding a stakeholder that owns the application also doesn't solve this since there's no way to set a password for those stakeholders. So you can't login as the stakeholder to get the access token. Even if you did login as a stakeholder, their access token probably wouldn't have permission to run an addon.

**Comment by jortel** [comment]
PR #207 adds a /hub/auth/login endpoint.  
> Adding a stakeholder that owns the application also doesn't solve this since there's no way to set a password for those stakeholders. So you can't login as the stakeholder to get the access token. Even if you did login as a stakeholder, their access token probably wouldn't have permission to run an addon.

You will still need to login as a user with permission to run tasks. I don't see any way around this.

**Comment by jortel** [comment]
Abandoned by author.
