### ISSUE TITLE
Restrict tag category colors to those supported by PatternFly.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#269]
Removes color generation from the hub and addon-windup.  Delegated to the UI.
Updated colors for seeded categories to be within supported PF colors.

**Comment by mansam** [comment]
We stopped generating color for newly imported TagCategories and those created by Windup in the following PRs:

https://github.com/konveyor/tackle2-hub/pull/279
https://github.com/konveyor/tackle2-addon-windup/pull/91

@mturley curated a list of 16 distinct colors and created a UI component that supports them. Changed the hub to seed TagCategories with those colors in #284.
