### ISSUE TITLE
Jira integration: Enable insecure communication field required

### ISSUE THREAD

**Issue by gildub** [konveyor/tackle2-hub#299]
Enhancement document for Jira integration : https://github.com/konveyor/enhancements/pull/85/files#diff-cbcdb511847ad0f355f71680ac0d8ccd22fd6f1792fe2b09c8d6c512970b82e4R32
requires a "Enable insecure communication" field for Jira instances.
It seems there is no such field in the current data model for trackers to support it.

**Comment by jortel** [comment]
Done.
