### ISSUE TITLE
Add E2E test using petclinic spring framework application

### ISSUE THREAD

**Issue by dymurray** [konveyor/tackle2-hub#304]
We want to add to the test suite a basic e2e test that uses [Petclinic](https://github.com/rromannissen/spring-framework-petclinic/tree/legacy) as an example. This e2e test should:
* Import application source
* Add a custom rule for hazelcast
* Run analysis
* Introspect the report to verify the rule was triggered

**Comment by jortel** [comment]
Should this be moved to github-actions repository?

**Comment by aufi** [comment]
This should be closed, the petclinic application was added to go-konveyor-tests with windup analyzer, it update to latest 0.3 release is tracked with https://github.com/konveyor/go-konveyor-tests/issues/39
