### ISSUE TITLE
Find right place for integration tests

### ISSUE THREAD

**Issue by aufi** [konveyor/tackle2-hub#310]
There is a ```test/integration``` directory with tests working with multiple Konveyor components using the Hub API.

There might be some part of integration tests relevant for the Hub, but majority of such tests is more or less Konveyor application-level E2E testing that should likely be in a separate repository. The exact place is to be discussed&agreed.

Related resources:
- https://github.com/konveyor/tackle2-hub/discussions/241
- https://github.com/konveyor/enhancements/pull/103
- https://github.com/konveyor/enhancements/pull/98

**Comment by aufi** [comment]
@dymurray @djzager The integration art of tests (with expected contribution from QE) should be moved from the Hub repo. Would prefer something else than https://github.com/konveyor/go-konveyor-tests?

**Comment by dymurray** [comment]
@aufi I think go-konveyor-tests seems like the most appropriate place to me. Any objections?

**Comment by djzager** [comment]
why don't they live with the component being tested?

**Comment by djzager** [comment]
Looking at [the comment that precipitated this issue](https://github.com/konveyor/tackle2-hub/pull/268#discussion_r1184958822), talking about the windup addon test not belonging in the hub. I believe the right answer is for the windup analysis integration test to live in the tackle2-addon-windup repo.

**Comment by aufi** [comment]
> The only test I see in the integration directory is a rewrite of the e2e test from the windup repo that was written in bash, now written in go...that we want to put into a 3rd repo.

That fits to my understanding, yes. The only existing rewritten test demonstrates that the integration works, but we're choosing a place for creating the test suite based on similar code as the existing test.

**Comment by aufi** [comment]
Analysis integration tests are continue in https://github.com/konveyor/go-konveyor-tests repository.
