### ISSUE TITLE
Add Integration test suite and components testing

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/tackle2-hub#312]
This issue has been moved. Please refer - https://github.com/konveyor/tackle2-operator/issues/220

**Comment by mohdaquib171** [comment]
Hello @savitharaghunathan @aufi and @djzager

I'm Mohd Aquib and I'm really excited about participating in the LFX mentorship program from June to August. I've been learning and working with Go for some time now and also have Basic software development skills (eg: CLI, GIT, etc) and would love to contribute to this project. Can you please suggest some resources and IRC channels that I can refer to? 

Your help would be greatly appreciated. 
Thank you!

**Comment by hackeramitkumar** [comment]
@savitharaghunathan @aufi @djzager 

I am Amit Kumar, and I am currently volunteering for the Cluster API v1.5 release team. I have also contributed as the release lead shadow for CAPI v1.4 release team in the past. Moreover, I was a GSoC 2022 student for AOSSIE.

I am writing to express my interest in applying for the upcoming LFX mentorship program. I have reviewed the proposal idea and would like to apply for it. However, I would appreciate it if you could inform me of any prerequisites for the proposal. I want to complete all the prerequisites before the mentoring session starts.

Thank you for your time and consideration. I look forward to hearing from you.

Best regards,
Amit Kumar

**Comment by jortel** [comment]
@savitharaghunathan I'm concerned that having this issue in the hub will invite application level (integration) tests being contributed here.

**Comment by savitharaghunathan** [comment]
> @savitharaghunathan I'm concerned that having this issue in the hub will invite application level (integration) tests being contributed here. If the intent is to invite contributions to the API tests, then please clarify in the description.

@jortel Thank you for bringing it up. To my knowledge, I dont think it is intended for API tests. I will move this issue to the right repo once its identified. 
@djzager @aufi Is there a repo that would be a better home for this issue?

**Comment by savitharaghunathan** [comment]
Closed in favor of https://github.com/konveyor/tackle2-operator/issues/220
