### ISSUE TITLE
Facts simplified.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#372]
Model: no changes.

Eliminates `Fact` resource.  Using `FactMap` resource already in use by _analysis_.

**Set fact (anonymous)**
GET  /applications/:id/facts/:key
returns value (object).

**Get fact (anonymous)**
PUT  /applications/:id/facts/:source/:key
body=value (object).

**Get fact (by source)**
GET /applications/:id/facts/:source/:key
returns value (object).

**Set fact (by source)**
PUT  /applications/:id/facts/:key
body=value (object).

**Get all facts (by source)**
GET  /applications/:id/facts/:source
returns `FactMap`

**Replace all facts (by source)**
PUT  /applications/:id/facts/:source
body `FactMap`

**Delete fact (anonymous)**
DELETE  /applications/:id/facts/:key

**Delete fact (by source)**
DELETE  /applications/:id/facts/:source/:key

**Comment by mansam** [comment]
Implemented by https://github.com/konveyor/tackle2-hub/pull/396

Facts are now identified by source-qualified keys in the format `source:name`. The source and separator may be left off to refer to an anonymous Fact.

The new endpoints are as follows, using `{}` as syntax for parameters to differentiate from literal `:` in keys.

## Anonymous Facts
**Create or replace fact**
PUT `/applications/{id}/facts/{name}`
body=value (object).

**Get fact**
GET `/applications/{id}/facts/{name}`
Returns value (object).

**Delete fact**
DELETE `/applications/{id}/facts/{name}`


## Qualified Facts
**Create or replace fact**
PUT `/applications/{id}/facts/{source}:{name}`
body=value (object).

**Get fact**
GET `/applications/{id}/facts/{source}:{name}`
Returns value (object).

**Delete fact**
DELETE `/applications/{id}/facts/{source}:{name}`

## Collections
**Get all facts for source**
GET `/applications/{id}/facts/{source}:`
Returns FactMap

**Replace all facts for source**
PUT `/applications/{id}/facts/{source}:`
body=FactMap
