### ISSUE TITLE
Analysis Archiving

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#428]
Goal.

When a new analyses is created, much of the previous report can/should be archived/summarized.
What does the archived analysis need to support:
- When/Who analyzed (history)?
- Effort burn-down?
- Number of issues burn-down? by category?
- Number of incidents burn-down?

Proposed archived information:
- createTime
- createUser
- effort
- []issues*:
  - ruleset
  - rule
  - name
  - description?
  - effort
  - category
  - number of incidents. 

*The storage for this would be relatively small.  The Incidents are the big data stored.  Each analysis will only have 1 issue per rule( that produced an issue).  This will likely be ~40-80 (or less) on average.

---

Proposal

Delete associated rows in Issue, Incident & TechDependency.
Store the _summary_ in Analysis.Summary JSON.

**Comment by mansam** [comment]
This approach sounds good to me.
