### ISSUE TITLE
:sparkles: Export/Import Assessments.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#489]
Update export/import to support assessments.
This is needed for migrating assessments from PathFinder to the Hub in tackle 0.3.

Prerequisite: Legacy Pathfinder questionnaire must be seeded.

The Pathfinder API offers an endpoint for retrieving assessments by application ID. This is accesssible from the Hub (pre-Custom Assessments) at `/pathfinder/assessments?applicationId=<id>`

An original Pathfinder assessment is described by these data structures. Comments indicate some of the fields that have different names in the new data model.:

```go
type LegacyAssessment struct {
    ID uint
    ApplicationID uint
    Status string
    Stakeholders []uint
    StakeholderGroups []uint
    Questionnaire Questionnaire
}

type Questionnaire struct {
    Categories []Category
    Title string // Corresponds to `Name` in the new model.
}

//
// Category corresponds to `Section` in the new data model.
type Category struct {
    ID uint // ignored
    Order uint
    Title string // corresponds to Section.Name
    Questions []Question
    Comment string // ignored
}

type Question struct {
    ID uint // ignored
    Order uint
    Question string // corresponds to Text
    Description string // corresponds to Explanation
    Options []Option
}

type Option struct {
    ID uint // ignored
    Order uint
    Option string // corresponds to Text
    Checked bool // corresponds to Selected
    Risk string // one-of RED,AMBER,GREEN,UNKNOWN (replaced by red,yellow,green,unknown in new model)
}
```

For each application, any assessment will have to be retrieved, converted to match the new Assessment API resource, and posted to the upgraded Hub with the Assessment's Questionnaire ref pointing to the seeded legacy questionnaire (ID 1).

**Comment by aufi** [comment]
Looks good, thanks for providing description 👍
