### ISSUE TITLE
Ensure api resources have consistent yaml tags as needed.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#533]
Ensure that all resources have yaml tags for camel cases field names and consistent _omitempty_.
Review all resources and add yaml tags as needed.
Ensure that composite structs are inlined properly

**Comment by RipulHandoo** [comment]
Hey @jortel.
I would like to take over this issue.
 Based on my understanding, the task involves ensuring that all resources in the codebase have proper YAML tags like [this](https://github.com/konveyor/tackle2-hub/blob/main/api/sort/sort.go#L12-#L15)
```
type Clause struct {
    Direction string `yaml:"direction,omitempty"`
    Name      string `yaml:"name,omitempty"`
}
```
Please let me know if I'm on the right track, and if there are any specific guidelines or details I should be aware of. I'm looking forward to contributing to this task.

**Comment by jortel** [comment]
Completed by @mansam
