### ISSUE TITLE
Update report dependencies endpoint to group by name only

### ISSUE THREAD

**Issue by sjd78** [konveyor/tackle2-hub#557]
For UI changes https://github.com/konveyor/tackle2-ui/issues/1338 and https://github.com/konveyor/tackle2-ui/issues/1340, the dependency table needs to display dependencies grouped by name only.  It currently displays rows based on name and sha.

Endpoint `/analyses/report/dependencies` is what is currently being used.  It returns struct:
```golang
//
// DepReport REST resource.
type DepReport struct {
	Provider     string   `json:"provider"`
	Name         string   `json:"name"`
	Version      string   `json:"version"`
	SHA          string   `json:"sha"`
	Labels       []string `json:"labels"`
	Applications int      `json:"applications"`
}
```
Please adjust the response to group dependencies by name only.  The `SHA` and `Version` fields are no longer needed.   The `Applications` count and `Labels` summary fields should also be adjusted.

Endpoint `/analyses/reports/dependencies/applications` is used by the application table on a dependency's details view.  This endpoint works as needed, but the response object has the dependency's sha named "rule":
```golang
//
// DepAppReport REST resource.
type DepAppReport struct {
	ID              uint   `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	BusinessService string `json:"businessService"`
	Dependency      struct {
		ID       uint     `json:"id"`
		Provider string   `json:"provider"`
		Name     string   `json:"name"`
		Version  string   `json:"version"`
		SHA      string   `json:"rule"`
		Indirect bool     `json:"indirect"`
		Labels   []string `json:"labels"`
	} `json:"dependency"`
}
```
Please rename the SHA field's json name to "sha".

**Comment by sjd78** [comment]
cc @ibolton336

**Comment by jortel** [comment]
Is the filter on:
- version
- sha

still needed?

**Comment by sjd78** [comment]
> Is the filter on:
> 
>     * version
> 
>     * sha
> 
> 
> still needed?

I don't think so... At the very least, they will not have a use on the dependencies table.
