### ISSUE TITLE
`builtin.Authenticate` panics if the Authorization header is missing or empty

### ISSUE THREAD

**Issue by mansam** [konveyor/tackle2-hub#619]
```go
// Authenticate the token
func (r *Builtin) Authenticate(request *Request) (jwToken *jwt.Token, err error) {
	token := strings.Replace(request.Token, "Bearer", "", 1)
	token = strings.Fields(token)[0]
```

If the Authorization header is missing or the string after replacement is nothing but whitespace, then `strings.Fields` will return an empty slice, and the attempt to index into it will panic. This should be fixed to return an auth failure.

**Comment by jortel** [comment]
I do not think changes to the AUTH layer is a  good first issue.
